package com.looptrip;

public enum PlanningEventType {
    ROUND_STARTED,
    TOOL_CALLED,
    GENERATION_STARTED,
    GENERATION_COMPLETED,
    SELECTION_COMPLETED,
    REVIEW_COMPLETED,
    FEEDBACK_PREPARED,
    COMPLETED,
    MAX_ROUNDS_REACHED
    ,PREFLIGHT_PASSED, GUARD_TRIGGERED, CANCEL_REQUESTED, CANCELLED,
    REVISION_STARTED, ROLLBACK_COMPLETED, HEARTBEAT
}
